baseURL: https://nathanisaac.io/
languageCode: en-us
title: Nathan Isaac
theme: "PaperMod"

params:
  defaultTheme: auto # dark, light

  # home-info mode
  homeInfoParams:
    Title: "Hey! I'm Nathan \U0001F44B"
    Content: Programmer, Photographer, Aviation Enthusiast

  socialIcons:
    - name: twitter
      url: "https://twitter.com/nathanjisaac"
    - name: github
      url: "https://github.com/nathan-isaac"
