baseURL: https://nathanisaac.io/
languageCode: en-us
title: Nathan Isaac
theme: "PaperMod"

params:
  defaultTheme: auto # dark, light
  DateFormat: "January 2, 2006"
  ShowReadingTime: true
  ShowWordCount: true
  hidemeta: false
  hideSummary: false
  ShowBreadCrumbs: true
  UseHugoToc: true



  # home-info mode
  homeInfoParams:
    Title: "Hey! I'm Nathan \U0001F44B"
    Content: Programmer, Photographer, Aviation Enthusiast

  socialIcons:
    - name: x
      url: "https://x.com/nathanjisaac"
    - name: github
      url: "https://github.com/nathan-isaac"
